services:
  - type: web
    name: agricola-luz-sombra
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt && cd agricola-frontend && npm install && npm run build && cd ..
    startCommand: python api.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /health
    autoDeploy: true
    branch: master
